# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-06 19:07
from __future__ import unicode_literals

import datetime
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('CreateTime', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('CreateUserId', models.IntegerField(null=True, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('IsDeleted', models.IntegerField(choices=[(0, '\u5220\u9664'), (1, '\u5b58\u5728')], default=1, verbose_name='\u662f\u5426\u5220\u9664')),
                ('MobileNumber', models.CharField(max_length=255, null=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('Name', models.CharField(max_length=255, verbose_name='\u59d3\u540d')),
                ('Remarks', models.CharField(max_length=255, null=True, verbose_name='\u4ecb\u7ecd')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True, verbose_name='\u90e8\u95e8\u4ee3\u7801')),
                ('ContactNumber', models.CharField(max_length=255, null=True, verbose_name='\u8054\u7cfb\u6570\u5b57')),
                ('CreateTime', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('CreateUserId', models.IntegerField(null=True, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('IsDeleted', models.IntegerField(choices=[(0, '\u5220\u9664'), (1, '\u5b58\u5728')], default=1, verbose_name='\u662f\u5426\u5220\u9664')),
                ('Manager', models.CharField(max_length=255, null=True, verbose_name='\u8d1f\u8d23\u4eba')),
                ('Name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('ParentId', models.IntegerField(null=True, verbose_name='\u7236\u90e8\u95e8id')),
                ('Remarks', models.CharField(max_length=255, null=True, verbose_name='\u4ecb\u7ecd')),
            ],
            options={
                'verbose_name': '\u90e8\u95e8\u4fe1\u606f',
                'verbose_name_plural': '\u90e8\u95e8\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=255, null=True, verbose_name='\u76ee\u5f55\u4ee3\u7801')),
                ('Icon', models.CharField(max_length=255, null=True)),
                ('Name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('ParentId', models.IntegerField(null=True, verbose_name='\u7236\u96c6\u76ee\u5f55id')),
                ('Remarks', models.CharField(max_length=255, null=True, verbose_name='\u4ecb\u7ecd')),
                ('SerialNumber', models.IntegerField()),
                ('Type', models.IntegerField()),
                ('Url', models.CharField(max_length=255, null=True, verbose_name='\u76ee\u5f55url')),
            ],
        ),
        migrations.CreateModel(
            name='MyRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=255, verbose_name='\u89d2\u8272\u4ee3\u7801')),
                ('CreateTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('CreateUserId', models.IntegerField(null=True, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('Name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('Remarks', models.CharField(max_length=255, verbose_name='\u4ecb\u7ecd')),
            ],
            options={
                'verbose_name': '\u89d2\u8272\u4fe1\u606f',
                'verbose_name_plural': '\u89d2\u8272\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='DepartmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Department', verbose_name='\u6240\u5c5e\u90e8\u95e8'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='MyRoleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MyRole'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
