# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-06 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='DepartmentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Department', verbose_name='\u6240\u5c5e\u90e8\u95e8'),
        ),
    ]
