# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-06 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170906_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '\u83dc\u5355\u4fe1\u606f', 'verbose_name_plural': '\u83dc\u5355\u4fe1\u606f'},
        ),
    ]
