# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-07 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RadioConstent',
            new_name='RadioContent',
        ),
    ]
