# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-06 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbacktitle', models.CharField(max_length=255, verbose_name='\u53cd\u9988\u9898\u76ee')),
                ('feedbackcontent', models.TextField(null=True, verbose_name='\u53cd\u9988\u5185\u5bb9')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='\u53cd\u9988\u7528\u6237')),
                ('feedback_timestamp', models.TimeField(verbose_name='\u52a0\u5165\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u53cd\u9988\u4fe1\u606f',
                'verbose_name_plural': '\u53cd\u9988\u4fe1\u606f',
            },
        ),
    ]
