# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-06 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelevisionProgramContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnails_url', models.URLField(max_length=255, verbose_name='\u7f29\u7565\u56feURL')),
                ('video_url', models.URLField(max_length=255, verbose_name='\u89c6\u9891URL')),
                ('video_introduction', models.CharField(max_length=255, verbose_name='\u89c6\u9891\u4ecb\u7ecd')),
                ('video_timestamp', models.TimeField(verbose_name='\u52a0\u5165\u65f6\u95f4')),
                ('note', models.CharField(max_length=255, null=True, verbose_name='\u8bf4\u660e')),
            ],
            options={
                'verbose_name': '\u7535\u89c6\u8282\u76ee\u5b9e\u4f53\u4fe1\u606f',
                'verbose_name_plural': '\u7535\u89c6\u8282\u76ee\u5b9e\u4f53\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='TelivisionProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('television_title', models.CharField(max_length=255, verbose_name='\u7535\u89c6\u8282\u76ee\u540d\u79f0')),
                ('note', models.CharField(max_length=255, null=True, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u7535\u89c6\u8282\u76ee\u4fe1\u606f',
                'verbose_name_plural': '\u7535\u89c6\u8282\u76ee\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='televisionprogramcontent',
            name='television_program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='televisions.TelivisionProgram', verbose_name='\u7535\u89c6\u8282\u76eeid'),
        ),
    ]
